# Generated by Django 2.0.9 on 2020-01-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
