# Generated by Django 2.0.9 on 2020-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letter', '0002_coverletter_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
