# Generated by Django 2.0.9 on 2019-12-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatFullTracker',
        ),
        migrations.RemoveField(
            model_name='chatpartone',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatpartonetracker',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatparttwo',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatPartOne',
        ),
        migrations.DeleteModel(
            name='ChatPartOneTracker',
        ),
        migrations.DeleteModel(
            name='ChatPartTwo',
        ),
        migrations.DeleteModel(
            name='SenderUUID',
        ),
    ]
