# Generated by Django 2.0.9 on 2019-12-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover_letter_tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicCoverLetter',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FullCoverLetter',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='OriginalFullCoverLetter',
        ),
        migrations.DeleteModel(
            name='PersonName',
        ),
        migrations.DeleteModel(
            name='RawCompany',
        ),
        migrations.DeleteModel(
            name='RawJobTitle',
        ),
        migrations.DeleteModel(
            name='RawPersonName',
        ),
        migrations.DeleteModel(
            name='UpdatedFullCoverLetter',
        ),
    ]
