# resume/urls.py
from django.conf.urls import url
from django.urls import path
# from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.views.decorators.csrf import csrf_exempt
# from .views import *

from jobassistant.resume.views import (
    create_personal_resume_form,
    update_personal_resume_form,
    personal_list,
    experience_resume_form,
    education_resume_form,
    reference_resume_form,
    positions_autocomplete,
    education_institutions_autocomplete,
    companies_autocomplete,
    resume_experience_list_api,
    resume_education_list_api,
    resume_reference_list_api,
    resume_personal_detail_api,
    create_tailored_pdf_resume_personal,
    create_tailored_pdf_resume_experience,
    create_tailored_pdf_resume_education,
    create_tailored_pdf_resume_reference,
)

app_name = 'resume'


urlpatterns = [
    path('personal/',
         create_personal_resume_form,
         name='create-personal'),
    url(r'personal/(?P<pk>[0-9]+)/$',
        update_personal_resume_form,
        name='personal-update'),
    path('personal/list',
         personal_list,
         name='list-personal'),
    path('experiences/',
         experience_resume_form,
         name='experiences'),
    path('educations/',
         education_resume_form,
         name='educations'),
    path('references/',
         reference_resume_form,
         name='references'),
    path('positions-autocomplete/',
         positions_autocomplete,
         name='positions-autocomplete'),
    path('education-institutions-autocomplete/',
         education_institutions_autocomplete,
         name='institutions-autocomplete'),
    path('companies-autocomplete/',
         companies_autocomplete,
         name='companies_autocomplete'),
    path('api-token-auth/',
         csrf_exempt(obtain_auth_token),
         name='api_token_auth',
         ),
    url(r'experience-api/(?P<candidate>[\w\-]+)/$',
        resume_experience_list_api,
        name='api-experience-list',
        ),
    url(r'education-api/(?P<candidate>[\w\-]+)/$',
        resume_education_list_api,
        name='api-education-list',
        ),
    url(r'reference-api/(?P<candidate>[\w\-]+)/$',
        resume_reference_list_api,
        name='api-reference-list',
        ),
    # url(r'personal-api/(?P<parent_user>[\w\-]+)/$',
    #     resume_personal_list_api,
    #     name='api-personal-list',
    #     ),
    url(r'personal-api/(?P<parent_user>[\w\-]+)/$',
        resume_personal_detail_api,
        name='api-personal-detail',
        ),
    url(r'create-tailored-personal/$',
        create_tailored_pdf_resume_personal,
        name='create-tailored-personal',
        ),
    url(r'create-tailored-experience/$',
        create_tailored_pdf_resume_experience,
        name='create-tailored-experience',
        ),
    url(r'create-tailored-education/$',
        create_tailored_pdf_resume_education,
        name='create-tailored-education',
        ),
    url(r'create-tailored-reference/$',
        create_tailored_pdf_resume_reference,
        name='create-tailored-reference',
        ),
]
