# Generated by Django 2.0.9 on 2019-01-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('currently_working_here', models.NullBooleanField()),
                ('position_description', models.TextField(max_length=500, null=True)),
                ('selected_accomplishment_1', models.CharField(max_length=300, null=True)),
                ('selected_accomplishment_2', models.CharField(max_length=300, null=True)),
                ('selected_accomplishment_3', models.CharField(max_length=300, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'industry categories',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('AFRIKAANS', 'Afrikaans'), ('ALBANIAN', 'Albanian'), ('AMHARIC', 'Amharic'), ('ARABIC', 'Arabic'), ('ARAMAIC', 'Aramaic'), ('ARMENIAN', 'Armenian'), ('ASSAMESE', 'Assamese'), ('AYMARA', 'Aymara'), ('AZERBAIJANI', 'Azerbaijani'), ('BALOCHI', 'Balochi'), ('BAMANANKAN', 'Bamanankan'), ('BASHKORT', 'Bashkort'), ('BASQUE', 'Basque'), ('BELARUSAN', 'Belarusan'), ('BENGALI', 'Bengali'), ('BHOJPURI', 'Bhojpuri'), ('BISLAMA', 'Bislama'), ('BOSNIAN', 'Bosnian'), ('BRAHUI', 'Brahui'), ('BULGARIAN', 'Bulgarian'), ('BURMESE', 'Burmese'), ('CANTONESE', 'Cantonese'), ('CATALAN', 'Catalan'), ('CEBUANO', 'Cebuano'), ('CHECHEN', 'Chechen'), ('CHEROKEE', 'Cherokee'), ('CROATIAN', 'Croatian'), ('CZECH', 'Czech'), ('DAKOTA', 'Dakota'), ('DANISH', 'Danish'), ('DARI', 'Dari'), ('DHOLUO', 'Dholuo'), ('DUTCH', 'Dutch'), ('ENGLISH', 'English'), ('ESPERANTO', 'Esperanto'), ('ESTONIAN', 'Estonian'), ('EWE', 'Ewe'), ('FINNISH', 'Finnish'), ('FRENCH', 'French'), ('GEORGIAN', 'Georgian'), ('GERMAN', 'German'), ('GIKUYU', 'Gikuyu'), ('GREEK', 'Greek'), ('GUARANI', 'Guarani'), ('GUJARATI', 'Gujarati'), ('HAITIAN', 'Haitian'), ('CREOLE', 'Creole'), ('HAUSA', 'Hausa'), ('HAWAIIAN', 'Hawaiian'), ('CREOLE', 'Creole'), ('HEBREW', 'Hebrew'), ('HILIGAYNON', 'Hiligaynon'), ('HINDI', 'Hindi'), ('HUNGARIAN', 'Hungarian'), ('ICELANDIC', 'Icelandic'), ('IGBO', 'Igbo'), ('ILOCANO', 'Ilocano'), ('INDONESIAN', 'Indonesian'), ('INUIT', 'Inuit'), ('IRISH', 'Irish'), ('GAELIC', 'Gaelic'), ('ITALIAN', 'Italian'), ('JAPANESE', 'Japanese'), ('JARAI', 'Jarai'), ('JAVANESE', 'Javanese'), ('KICHE', 'Kiche'), ('KABYLE', 'Kabyle'), ('KANNADA', 'Kannada'), ('KASHMIRI', 'Kashmiri'), ('KAZAKH', 'Kazakh'), ('KHMER', 'Khmer'), ('KHOEKHOE', 'Khoekhoe'), ('KOREAN', 'Korean'), ('KURDISH', 'Kurdish'), ('KYRGYZ', 'Kyrgyz'), ('LAO', 'Lao'), ('LATIN', 'Latin'), ('LATVIAN', 'Latvian'), ('LINGALA', 'Lingala'), ('LITHUANIAN', 'Lithuanian'), ('MACEDONIAN', 'Macedonian'), ('MAITHILI', 'Maithili'), ('MALAGASY', 'Malagasy'), ('MALAY', 'Malay'), ('MALAYALAM', 'Malayalam'), ('MANDARIN', 'Mandarin'), ('MARATHI', 'Marathi'), ('MENDE', 'Mende'), ('MONGOLIAN', 'Mongolian'), ('NAHUATL', 'Nahuatl'), ('NAVAJO', 'Navajo'), ('NEPALI', 'Nepali'), ('NORWEGIAN', 'Norwegian'), ('OJIBWA', 'Ojibwa'), ('ORIYA', 'Oriya'), ('OROMO', 'Oromo'), ('PASHTO', 'Pashto'), ('PERSIAN', 'Persian'), ('POLISH', 'Polish'), ('PORTUGUESE', 'Portuguese'), ('PUNJABI', 'Punjabi'), ('QUECHUA', 'Quechua'), ('ROMANI', 'Romani'), ('ROMANIAN', 'Romanian'), ('RUSSIAN', 'Russian'), ('RWANDA', 'Rwanda'), ('SAMOAN', 'Samoan'), ('SANSKRIT', 'Sanskrit'), ('SERBIAN', 'Serbian'), ('SHONA', 'Shona'), ('SINDHI', 'Sindhi'), ('SINHALA', 'Sinhala'), ('SLOVAK', 'Slovak'), ('SLOVENE', 'Slovene'), ('SOMALI', 'Somali'), ('SPANISH', 'Spanish'), ('SWAHILI', 'Swahili'), ('SWEDISH', 'Swedish'), ('TACHELHIT', 'Tachelhit'), ('TAGALOG', 'Tagalog'), ('TAJIKI', 'Tajiki'), ('TAMIL', 'Tamil'), ('TATAR', 'Tatar'), ('TELUGU', 'Telugu'), ('THAI', 'Thai'), ('TIBETIC', 'Tibetic'), ('TIGRIGNA', 'Tigrigna'), ('TOK', 'Tok'), ('PISIN', 'Pisin'), ('TURKISH', 'Turkish'), ('TURKMEN', 'Turkmen'), ('UKRAINIAN', 'Ukrainian'), ('URDU', 'Urdu'), ('UYGHUR', 'Uyghur'), ('UZBEK', 'Uzbek'), ('VIETNAMESE', 'Vietnamese'), ('WARLPIRI', 'Warlpiri'), ('WELSH', 'Welsh'), ('WOLOF', 'Wolof'), ('XHOSA', 'Xhosa'), ('YAKUT', 'Yakut'), ('YIDDISH', 'Yiddish'), ('YORUBA', 'Yoruba'), ('YUCATEC', 'Yucatec'), ('ZAPOTEC', 'Zapotec'), ('ZULU', 'Zulu')], max_length=200, null=True)),
                ('level', models.CharField(choices=[('ELEMENTARY PROFICIENCY', 'Elementary Proficiency'), ('LIMITED WORKING PROFICIENCY', 'Limited Working Proficiency'), ('MINIMUM PROFESSIONAL PROFICIENCY', 'Minimum Professional Proficiency'), ('FULL PROFESSIONAL PROFICIENCY', 'Full Professional Proficiency'), ('NATIVE OR BILINGUAL PROFICIENCY', 'Native or Bilingual Proficiency')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=120, null=True)),
                ('state', models.CharField(max_length=120, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=120, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('profile_summary', models.TextField(max_length=500, null=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'positions',
            },
        ),
        migrations.CreateModel(
            name='ReconciledPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_positions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Positions')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Personal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubIndustryCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.IndustryCategories')),
            ],
            options={
                'verbose_name_plural': 'sub-industry categories',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='resume.Skills', to='taggit.Tag', verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='language',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Personal'),
        ),
        migrations.AddField(
            model_name='experience',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.IndustryCategories'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Positions'),
        ),
        migrations.AddField(
            model_name='experience',
            name='subindustry',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='industry', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.SubIndustryCategories'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.EducationInstitutions'),
        ),
    ]
