# Generated by Django 2.0.9 on 2019-04-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
    ]
