# Generated by Django 2.0.9 on 2019-04-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190409_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResumePDFBodyEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=100, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('start_date', models.CharField(max_length=100, null=True)),
                ('end_date', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailoredResumePDFBodyExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('start_date', models.CharField(max_length=100, null=True)),
                ('end_date', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('selected_accomplishment_1', models.CharField(max_length=500, null=True)),
                ('selected_accomplishment_2', models.CharField(max_length=500, null=True)),
                ('selected_accomplishment_3', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailoredResumePDFBodyReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=100, null=True)),
                ('candidate', models.CharField(max_length=100, null=True)),
                ('current_position', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profile_summary',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
