# Generated by Django 2.0.9 on 2019-04-11 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190411_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResumePDFPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('languages', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TailoredResumePDFBodyEducation',
            new_name='TailoredResumePDFEducation',
        ),
        migrations.RenameModel(
            old_name='TailoredResumePDFBodyExperience',
            new_name='TailoredResumePDFExperience',
        ),
        migrations.RenameModel(
            old_name='TailoredResumePDFBodyReference',
            new_name='TailoredResumePDFReference',
        ),
        migrations.AlterField(
            model_name='language',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.Personal'),
        ),
    ]
