# Generated by Django 2.0.9 on 2019-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20190411_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresumepdfexperience',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tailoredresumepdfexperience',
            name='position_description',
            field=models.TextField(null=True),
        ),
    ]
