# Generated by Django 2.0.9 on 2019-04-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20190411_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresumepdfpersonal',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
