# Generated by Django 2.0.9 on 2019-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20190411_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresumepdfreference',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
