# Generated by Django 2.0.9 on 2019-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_tailoredresumepdfreference_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_date',
            new_name='education_end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='education_start_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='end_date',
            new_name='work_start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='work_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='selected_accomplishment_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
