# Generated by Django 2.0.9 on 2019-07-12 03:56

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resume', '0011_auto_20190704_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='resume.TaggedTools', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='taggedtools',
            name='content_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Tools'),
        ),
        migrations.AddField(
            model_name='taggedtools',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_taggedtools_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Tools'),
        ),
    ]
