# Generated by Django 2.0.9 on 2019-07-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20190712_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedtools',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedtools',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='tags',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='tags',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='tools',
        ),
        migrations.AlterField(
            model_name='skills',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resume.Personal'),
        ),
        migrations.DeleteModel(
            name='TaggedTools',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
