# Generated by Django 2.0.9 on 2019-07-12 04:47

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resume', '0013_auto_20190712_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools+', to='resume.Personal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_tools_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='tools',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tools+', through='resume.Tools', to='taggit.Tag', verbose_name='tools'),
        ),
    ]
