# Generated by Django 2.0.9 on 2019-07-12 04:51

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resume', '0014_auto_20190712_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='skills',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='tag',
        ),
        migrations.AlterField(
            model_name='personal',
            name='skills',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='resume.Skill', to='taggit.Tag', verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tools',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tools+', through='resume.Tool', to='taggit.Tag', verbose_name='tools'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AddField(
            model_name='tool',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools+', to='resume.Personal', verbose_name='tools'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_tool_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='skill',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills+', to='resume.Personal', verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skill_items', to='taggit.Tag'),
        ),
    ]
