# Generated by Django 2.0.9 on 2019-07-12 06:50

from django.db import migrations, models
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20190712_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='skills',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='skills+', through='resume.Skill', to='taggit.Tag', verbose_name='skills'),
        ),
    ]
