# Generated by Django 2.0.9 on 2019-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20190712_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresumepdfpersonal',
            name='tools',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
