# Generated by Django 2.0.9 on 2019-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_tailoredresumepdfpersonal_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
