# Generated by Django 2.0.9 on 2019-07-23 08:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_auto_20190712_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg. +61XXXXXXXXX', max_length=128, region=None),
        ),
    ]
